// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Infra.Database;

#nullable disable

namespace Sistema.Infra.Database.Migrations
{
    [DbContext(typeof(SistemaDbContext))]
    partial class SistemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Domain.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.TelefoneTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TelefoneTipos", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaTrocaSenha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid(36)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ListaIps")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("QuantidadeTentativasLogin")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrocarSenha")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UsuarioPerfilId")
                        .HasColumnType("uuid(36)");

                    b.Property<Guid?>("UsuarioTrocaSenhaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("VerificaIP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VerificaMacAddress")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioPerfilId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("UsuarioPerfis", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioPerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("UsuarioPerfilId")
                        .HasColumnType("uuid(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioPerfilId");

                    b.ToTable("UsuarioPerfilAcessos", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioTelefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlgStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TelefoneTipoId")
                        .HasColumnType("uuid(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid(36)");

                    b.HasKey("Id");

                    b.HasIndex("TelefoneTipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioTelefones", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Domain.Entities.UsuarioPerfil", "UsuarioPerfil")
                        .WithMany()
                        .HasForeignKey("UsuarioPerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("UsuarioPerfil");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioPerfilAcesso", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.UsuarioPerfil", null)
                        .WithMany("UsuarioPerfilAcessos")
                        .HasForeignKey("UsuarioPerfilId");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioTelefone", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.TelefoneTipo", "TelefoneTipo")
                        .WithMany()
                        .HasForeignKey("TelefoneTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioTelefones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelefoneTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioTelefones");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Navigation("UsuarioPerfilAcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
